spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.35.207:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$

server:
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /api-docs
    urls:
      - url: /v3/api-docs/0000. 공통
        name: 0000. 공통
      - url: /v3/api-docs/0100. 커뮤니티
        name: 0100. 커뮤니티
      - url: /v3/api-docs/0200. 메뉴
        name: 0200. 메뉴
      - url: /v3/api-docs/0300. 주문
        name: 0300. 주문
      - url: /v3/api-docs/0400. 상품
        name: 0400. 상품

  group-configs:
    - group: 0000. 공통
      paths-to-match: /api/common/**
    - group: 0100. 커뮤니티
      paths-to-match: /api/community/**
    - group: 0200. 메뉴
      paths-to-match: /api/menu/**
    - group: 0300. 주문
      paths-to-match:
        - /api/order/**
        - /api/order
    - group: 0400. 상품
      paths-to-match:
        - /api/product/**
        - /api/product

