server:
  port: 8080

spring:
  profiles:
    active: local

mybatis:
  mapper-locations: classpath*:/kr/co/winnticket/**/*.xml
  type-aliases-package: kr.co.winnticket
  configuration:
    map-underscore-to-camel-case: true
    type-handlers-package: kr.co.winnticket.common.typehandler

logging:
  level:
    kr.co.winnticket: DEBUG