server:
  port: 8080
  url: https://api.winnticket.store
  logging:
    level:
      root: DEBUG

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.36.128.67:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$

  redis:
    data:
      host: localhost
      port: 6379
      password: null

file:
  upload-dir: /Users/kimhb/uploads

  jwt:
    secret: ${JWT_SECRET}

# 채널 연동 (베네피아)
benepia:
  seed-key: 93bf2sd0324em312
  cust-co-cd: z381
  confirm-url: https://stg-auth.benepia.co.kr/api/token/confirm
  token-create-url: https://stg-auth.benepia.co.kr/api/token/request
  batch-base-url: https://stg-collections.benepia.co.kr
  prdgb-file: ticket
  kcp-co-cd: A8MCD

# 신용카드 연동
payletter:
  base-url: https://testpgapi.payletter.com #운영 : https://pgapi.payletter.com/
  client-id: pay_test
  payment-api-key: MTFBNTAzNTEwNDAxQUIyMjlCQzgwNTg1MkU4MkZENDA=
  search-api-key: MUI3MjM0RUExQTgyRDA1ODZGRDUyOEM4OTY2QTVCN0Y=
  service-name: 페이레터

  return-url: https://api.winnticket.store/api/payletter/return
  callback-url: https://api.winnticket.store/api/payletter/callback
  cancel-url: https://api.winnticket.store/api/payletter/cancel

# 파트너 연동 (플러스앤)
plusn:
  base-url: http://partnerdev.tourok.co.kr   # 운영 : https://partner.tourok.co.kr
  order-company: "148"

# 파트너 연동 (민속촌 코어웍스)
coreworks:
  base-url: http://dev-api.core-works.co.kr:8050 # 운영 : https://api.core-works.co.kr/channel/general/v11/order
  auth-token: "1505ee1f89cc000efdda3b34ee2485fbd9e50be4943ad0c9acf3ceab7bfc225a"
  channel-cd: "HYUNDAINTOUR"

# 파트너 연동 (웅진)
woongjin:
  base-url: https://channel-api.nolbal.com # 토큰만 다른거같음..?
  api-token: "bm9sYmFsLTIyLTIwMjUtMDMtMjRUMDc6NTQ6NDAuNjcwMzkz"

# 파트너 연동 (엠에어)
mair:
  mode: prod # dev | prod
  mkno: "HDGH"     # 채널 구분 코드
  mkid: "HDGH1"    # 채널 아이디
  connectTimeoutMs: 2000
  responseTimeoutMs: 5000
  issueUrl: "https://cp.mair.co.kr/dev/_cp_jsonp.asp" # 운영 : https://cp.mair.co.kr/_cp_jsonp.asp
  cancelUrl: "https://cp.mair.co.kr/dev/_cp_cc_jsonp.asp" # 운영 : https://cp.mair.co.kr/_cp_cc_jsonp.asp
  useCheckUrl: "https://cp.mair.co.kr/dev/_cp_use_jsonp.asp" # 운영 : https://cp.mair.co.kr/_cp_use_jsonp.asp

# 파트너 연동 (스파비스)
spavis:
  base-url: "https://www.spavis.co.kr/social_interface/couponif03.asp" # 스파비스 운영 url
  cust-id: 410268 # 채널 코드

# 파트너 연동 (플레이스토리)
playstory:
  base-url: "http://out.dev.pscms.co.kr"
  chn-id: "hyundaiplanandtour"

# 파트너 연동 (스마트인피니(서울랜드))
smartinfini:
  base-url: "https://nsi.smartinfini.com/cinterface"
  token: "BZIG91YGLkcts0U2Uau5Kg=="
  channel-id : "36"

# 뱅크다 연동
bankda:
  url: "https://a.bankda.com/dtsvc/bank_tr.php"
  token: "d4545a3900b2f4b8ce3df4b28db4f8c7"
