server:
  forward-headers-strategy: framework
  port: 8080

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.35.207:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$

  redis:
    data:
      redis:
        host: 127.0.0.1
        port: 6347
        password: null

file:
  base-url: https://cdn.winnticket.store
  upload-path: /home/ubuntu/winnticket_upload


