server:
  port: 8080
  url: https://api.winnticket.store
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        same-site: none
        secure: true
spring:
  profiles:
    active: local   # 기본은 local

mybatis:
  mapper-locations: classpath*:/**/*Sql.xml
  type-aliases-package: kr.co.winnticket
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: kr.co.winnticket.common.typehandler

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs
  group-configs: []
    
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: false

jwt:
  #secret: ${JWT_SECRET:local-secret}
  secret: fW8Lr3RkZJq92xu3x6Qm2TZZV9DPuG3EJm1Q8zv9pO4Z6rjVJt5vZkBj0U9y3BTsPR3A1GjWJq8N0Kj7WTfF1Q
  access-token-validity: 3600000 #1시간
  refresh-token-validity: 2592000000 #30일

logging:
  level:
    kr.co.winnticket: DEBUG

file:
  upload-dir: /Users/kimhb/uploads

benepia:
  seed-key: 93bf2sd0324em312
  cust-co-cd: z381
  confirm-url: https://stg-auth.benepia.co.kr/api/token/confirm
  token-create-url: https://stg-auth.benepia.co.kr/api/token/request
  batch-base-url: https://stg-collections.benepia.co.kr
  prdgb-file: ticket
  kcp-co-cd: A8MCD

payletter:
  base-url: https://testpgapi.payletter.com
  client-id: auto_test1
  payment-api-key: NUMzRDJFQzVERkRBNTQzQjY1MkUzMTQ3NThFREU2Mzg=
  service-name: 페이레터

  return-url: https://api.winnticket.store/payletter/return
  callback-url: https://api.winnticket.store/payletter/callback
  cancel-url: https://api.winnticket.store/payletter/cancel

# 파트너 연동 (플러스앤)
plusn:
  base-url: http://partnerdev.tourok.co.kr   # 운영 : https://partner.tourok.co.kr
  order-company: "148"

# 파트너 연동 (민속촌 코어웍스)
coreworks:
  base-url: http://dev-api.core-works.co.kr:8050 # 운영 : https://api.core-works.co.kr/channel/general/v11/order
  auth-token: "1505ee1f89cc000efdda3b34ee2485fbd9e50be4943ad0c9acf3ceab7bfc225a" #운영 : 59bee29ea0f864ad803b8af2ff1f029d51dba857a2732015b286f4f622a1f094
  channel-cd: "HYUNDAINTOUR"