spring:
  config:
    activate:
      on-profile: dev

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.31.35.207:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$

springdoc:
  servers:
    - url: https://api.winnticket.store
      description: 개발 서버

  group-configs:
    - group: 0000. 공통
      paths-to-match: /api/common/**
    - group: 0100. 커뮤니티
      paths-to-match: /api/community/**
    - group: 0200. 메뉴
      paths-to-match: /api/menu/**
