server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.36.128.67:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$


mybatis:
  mapper-locations: classpath*:/kr/co/winnticket/**/*.xml
  type-aliases-package: kr.co.winnticket
  configuration:
    map-underscore-to-camel-case: true
    type-handlers-package: kr.co.winnticket.common.typehandler


logging:
  level:
    kr.co.winnticket: DEBUG