server:
  port: 8080

spring:
  profiles:
    active: local   # 기본은 local

mybatis:
  mapper-locations: classpath*:/**/*Sql.xml
  type-aliases-package: kr.co.winnticket
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: kr.co.winnticket.common.typehandler

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /api-docs

  group-configs:
    - group: 공통
      paths-to-match: /api/common/**
    - group: 커뮤니티
      paths-to-match: /api/community/**
    - group: 메뉴
      paths-to-match: /api/menu/**
    - group: 주문
      paths-to-match: /api/order/**
    - group: 상품
      paths-to-match: /api/product/**
    - group: 로그인 및 토큰
      paths-to-match: /api/auth/**
    - group: 사이트관리
      paths-to-match: /api/admin/**
    - group: 파트너관리
      paths-to-match: /api/partners/**
    - group: 채널관리
      paths-to-match: /api/channels/**

  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  override-with-generic-response: false

jwt:
  #secret: ${JWT_SECRET:local-secret}
  secret: fW8Lr3RkZJq92xu3x6Qm2TZZV9DPuG3EJm1Q8zv9pO4Z6rjVJt5vZkBj0U9y3BTsPR3A1GjWJq8N0Kj7WTfF1Q
  access-token-validity: 3600000 #1시간
  refresh-token-validity: 2592000000 #30일

logging:
  level:
    kr.co.winnticket: DEBUG

file:
  upload-dir: /Users/kimhb/uploads
