server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    #driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://winnticket-prod-db.c5ykoswqgy2y.ap-northeast-2.rds.amazonaws.com:5432/winnticket_prod
    username: winnticket
    password: ${DB_PASSWORD}

  Jpa:
    open-in-view: false

  data:
    redis:
      host: 127.0.0.1
      port: 6379


logging:
  level:
    kr.co.winnticket: debug
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: 18000000 #1800000 #30분
  refresh-token-validity: 1209600000 #7일

# S3 이미지
cloud:
  aws:
    region:
      static: ap-northeast-2
    s3:
      bucket: winnticket-prod-uploads

# CloudFront URL
cdn:
  url: https://d2f2qj7j8l0gx6.cloudfront.net


# 채널 연동 (베네피아 운영)
benepia:
  seed-key: ${BENEPIA_SEED_KEY}
  cust-co-cd: z381
  confirm-url: https://auth.benepia.co.kr/api/token/confirm
  token-create-url: https://auth.benepia.co.kr/api/token/request
  batch-base-url: https://collections.benepia.co.kr
  prdgb-file: ticket
  kcp-co-cd: A8MCD


# 신용카드 연동 (페이레터 운영)

payletter:
  base-url: https://pgapi.payletter.com
  client-id: pay_test #운영은 문의해봐야함
  payment-api-key: ${PAYLETTER_PAYMENT_API_KEY}
  search-api-key: ${PAYLETTER_SEARCH_API_KEY}
  service-name: 페이레터

  return-url: https://api.winnticket.co.kr/api/payletter/return
  callback-url: https://api.winnticket.co.kr/api/payletter/callback
  cancel-url: https://api.winnticket.co.kr/api/payletter/cancel


# 파트너 연동 (플러스앤 운영)
plusn:
  base-url: https://partner.tourok.co.kr
  order-company: "148"

# 파트너 연동 (코어웍스 운영)
coreworks:
  base-url: https://api.core-works.co.kr/channel/general/v11/order
  auth-token: ${COREWORKS_AUTH_TOKEN}
  channel-cd: HYUNDAINTOUR

# 파트너 연동 (웅진 운영)
woongjin:
  base-url: https://channel-api.nolbal.com
  api-token: ${WOONGJIN_API_TOKEN}

# 엠에어 운영
mair:
  mode: prod
  mkno: HDGH
  mkid: HDGH1
  connectTimeoutMs: 2000
  responseTimeoutMs: 5000
  issueUrl: https://cp.mair.co.kr/_cp_jsonp.asp
  cancelUrl: https://cp.mair.co.kr/_cp_cc_jsonp.asp
  useCheckUrl: https://cp.mair.co.kr/_cp_use_jsonp.asp

# 파트너 연동 (스파비스)
spavis:
  base-url: "https://www.spavis.co.kr/social_interface/couponif03.asp"
  cust-id: 410268

# 파트너 연동 (플레이스토리)
playstory:
  base-url: "https://storeapi.pscms.co.kr"
  chn-id: "P240076"

# 뱅크다 연동
bankda:
  url: "https://a.bankda.com/dtsvc/bank_tr.php"
  token: "369fe06f41dbe5efc7b69a28da47bb2f"


# 파트너 연동 (아쿠아플라넷)
aquaplanet:
  base-url: "https://exgate.hanhwaresort.co.kr:443/iGate/SIF/json.jdo" # 운영

  # 공통 fixed 값들(문서의 Setting Value)
  tmsg-ver-dv-cd: "01"
  envr-info-dv-cd: "R"          # D:개발 / R:운영
  lang-cd: "KO"
  stn-msg-encp-cd: "0"
  stn-msg-comp-cd: "0"
  std-tmsg-prgr-no: "00"
  frs-rqst-sys-cd: "SIF"
  trsc-sync-dv-cd: "S"
  rqst-rsps-dv-cd: "S"

  stn-msg-tr-tp-cd: "O"         # 온라인
  system-type: "HABIS"
  mask-auth: "0"

  wrkr-no: "I711019"
  recv-svc-cd-contract: "HBSSAMCNT0114"
  intf-id-contract: "SIF00HBSSAMCNT0114"

  recv-svc-cd-issue: "HBSSAMCPN0306"
  intf-id-issue: "SIF00HBSSAMCPN0306"

  recv-svc-cd-cancel: "HBSSAMCPN1003"
  intf-id-cancel: "SIF00HBSSAMCPN1003"

  recv-svc-cd-use-history: "HBSSAMCPN1100"
  intf-id-use-history: "SIF00HBSSAMCPN1100"

  recv-svc-cd-use-daily-history: "HBSSAMCPN1103"
  intf-id-use-daily-history: "SIF00HBSSAMCPN1103"

