server:
  port: 8080
  url: https://api.winnticket.store
  logging:
    level:
      root: DEBUG

spring:
  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://3.36.128.67:5432/winnticket?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: admin
    password: winnticket!@#$

  redis:
    data:
     host: localhost
     port: 6379
     password: null


# Benepia 연동 (local 테스트용)
benepia:
  base-url: https://auth.benepia.co.kr
  cust-co-cd: z381
  seed-key: 93bf2sd0324em312
  plain-charset: EUC-KR


