server:
  port: 8080
  url: https://api.winnticket.store
  servlet:
    session:
      cookie:
        name: JSESSIONID
        path: /
        same-site: none
        secure: true

spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 30MB

mybatis:
  mapper-locations:
    classpath:/kr/co/winnticket/**/*.xml
  type-aliases-package: kr.co.winnticket
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: kr.co.winnticket.common.typehandler

jwt:
  access-token-validity: 3600000 #1시간
  refresh-token-validity: 2592000000 #30일

logging:
  level:
    kr.co.winnticket: DEBUG